### ISSUE TITLE
'Info' side of the embed card produces no output in Firefox

### ISSUE THREAD

**Issue by Complexity** [ProjectOpenSea/embeddable-nfts#31]
When embedding NFTs from Opensea using the suggested HTML snippet, whilst both sides of the embed work in Chrome, Brave, Safari, the "Info" side that flips and presents after clicking the info icon produces blank output in Firefox browsers.

For example, from the Opensea announcement post (https://opensea.io/blog/announcements/announcing-embeddable-nfts/):

Chrome (good output):

<img width="950" alt="Screenshot 2021-06-07 at 14 59 54" src="https://user-images.githubusercontent.com/756897/121030442-626e7400-c7a1-11eb-83d4-1a4786370dd9.png">

Brave (good output):

<img width="849" alt="Screenshot 2021-06-07 at 15 00 07" src="https://user-images.githubusercontent.com/756897/121030509-71552680-c7a1-11eb-8907-88044b6584d0.png">

Firefox (90.3) (failed output):

<img width="949" alt="Screenshot 2021-06-07 at 15 00 23" src="https://user-images.githubusercontent.com/756897/121030649-934ea900-c7a1-11eb-9fc5-4447dcc36fe1.png">

**Comment by Complexity** [comment]
Toggling .card-back hidden attribute manually to disabled produces the expected content.

<img width="344" alt="Screenshot 2021-06-07 at 15 18 03" src="https://user-images.githubusercontent.com/756897/121034430-ee35cf80-c7a4-11eb-8b0a-76f117faba95.png">

**Comment by fafrd** [comment]
Actually it looks like flipping is totally broken right now, in both chrome+firefox

**Comment by fafrd** [comment]
Fixed
