### ISSUE TITLE
<nft-card     contractAddress="0xc36442b4a4522e871399cd717abdd847ab11fe88"     tokenId="4062">     </nft-card>     <script src="https://unpkg.com/embeddable-nfts/dist/nft-card.min.js"></script>

### ISSUE THREAD

**Issue by ggj883** [ProjectOpenSea/embeddable-nfts#33]

**Comment by Dunlap28** [comment]
<nft-card contractAddress="0xf9703fbceda236abe22a8aae2cc425dae5e6e5a4" tokenId="4900120009"> </nft-card> <script src="https://unpkg.com/embeddable-nfts/dist/nft-card.min.js"></script>
