### ISSUE TITLE
Node version

### ISSUE THREAD

**Issue by wyandun** [ProjectOpenSea/embeddable-nfts#38]
I have tried to install the project but it does not work with my current version of node, I have 15.11.0, how can I run the project?

**Comment by zeddvandaar** [comment]
temp solution:
1. install nvm - https://github.com/nvm-sh/nvm
2. install node 14 - nvm install 14
3. enjoy

**Comment by fafrd** [comment]
We recommend you use `yarn` for this project. I'll update the readme to reflect this
